USE so_videojuegos;

INSERT INTO paises (nombre, dominio) VALUES
		("Afganistán","AF"),
		("Albania","AL"),
		("Alemania","DE"),
		("Andorra","AD"),
		("Angola","AO"),
		("Anguila","AI"),
		("Antártida","AQ"),
		("Antigua y Barbuda","AG"),
		("Arabia Saudita","SA"),
		("Argelia","DZ"),
		("Argentina","AR"),
		("Armenia","AM"),
		("Aruba","AW"),
		("Australia","AU"),
		("Austria","AT"),
		("Azerbaiyán","AZ"),
		("Bélgica","BE"),
		("Bahamas","BS"),
		("Bahrein","BH"),
		("Bangladesh","BD"),
		("Barbados","BB"),
		("Belice","BZ"),
		("Benín","BJ"),
		("Bhután","BT"),
		("Bielorrusia","BY"),
		("Birmania","MM"),
		("Bolivia","BO"),
		("Bosnia y Herzegovina","BA"),
		("Botsuana","BW"),
		("Brasil","BR"),
		("Brunéi","BN"),
		("Bulgaria","BG"),
		("Burkina Faso","BF"),
		("Burundi","BI"),
		("Cabo Verde","CV"),
		("Camboya","KH"),
		("Camerún","CM"),
		("Canadá","CA"),
		("Chad","TD"),
		("Chile","CL"),
		("China","CN"),
		("Chipre","CY"),
		("Ciudad del Vaticano","VA"),
		("Colombia","CO"),
		("Comoras","KM"),
		("República del Congo","CG"),
		("República Democrática del Congo","CD"),
		("Corea del Norte","KP"),
		("Corea del Sur","KR"),
		("Costa de Marfil","CI"),
		("Costa Rica","CR"),
		("Croacia","HR"),
		("Cuba","CU"),
		("Curazao","CW"),
		("Dinamarca","DK"),
		("Dominica","DM"),
		("Ecuador","EC"),
		("Egipto","EG"),
		("El Salvador","SV"),
		("Emiratos Árabes Unidos","AE"),
		("Eritrea","ER"),
		("Eslovaquia","SK"),
		("Eslovenia","SI"),
		("España","ES"),
		("Estados Unidos de América","US"),
		("Estonia","EE"),
		("Etiopía","ET"),
		("Filipinas","PH"),
		("Finlandia","FI"),
		("Fiyi","FJ"),
		("Francia","FR"),
		("Gabón","GA"),
		("Gambia","GM"),
		("Georgia","GE"),
		("Ghana","GH"),
		("Gibraltar","GI"),
		("Granada","GD"),
		("Grecia","GR"),
		("Groenlandia","GL"),
		("Guadalupe","GP"),
		("Guam","GU"),
		("Guatemala","GT"),
		("Guayana Francesa","GF"),
		("Guernsey","GG"),
		("Guinea","GN"),
		("Guinea Ecuatorial","GQ"),
		("Guinea-Bissau","GW"),
		("Guyana","GY"),
		("Haití","HT"),
		("Honduras","HN"),
		("Hong kong","HK"),
		("Hungría","HU"),
		("India","IN"),
		("Indonesia","ID"),
		("Irán","IR"),
		("Irak","IQ"),
		("Irlanda","IE"),
		("Isla Bouvet","BV"),
		("Isla de Man","IM"),
		("Isla de Navidad","CX"),
		("Isla Norfolk","NF"),
		("Islandia","IS"),
		("Islas Bermudas","BM"),
		("Islas Caimán","KY"),
		("Islas Cocos (Keeling)","CC"),
		("Islas Cook","CK"),
		("Islas de Åland","AX"),
		("Islas Feroe","FO"),
		("Islas Georgias del Sur y Sandwich del Sur","GS"),
		("Islas Heard y McDonald","HM"),
		("Islas Maldivas","MV"),
		("Islas Malvinas","FK"),
		("Islas Marianas del Norte","MP"),
		("Islas Marshall","MH"),
		("Islas Pitcairn","PN"),
		("Islas Salomón","SB"),
		("Islas Turcas y Caicos","TC"),
		("Islas Ultramarinas Menores de Estados Unidos","UM"),
		("Islas Vírgenes Británicas","VG"),
		("Islas Vírgenes de los Estados Unidos","VI"),
		("Israel","IL"),
		("Italia","IT"),
		("Jamaica","JM"),
		("Japón","JP"),
		("Jersey","JE"),
		("Jordania","JO"),
		("Kazajistán","KZ"),
		("Kenia","KE"),
		("Kirguistán","KG"),
		("Kiribati","KI"),
		("Kuwait","KW"),
		("Líbano","LB"),
		("Laos","LA"),
		("Lesoto","LS"),
		("Letonia","LV"),
		("Liberia","LR"),
		("Libia","LY"),
		("Liechtenstein","LI"),
		("Lituania","LT"),
		("Luxemburgo","LU"),
		("México","MX"),
		("Mónaco","MC"),
		("Macao","MO"),
		("Macedônia","MK"),
		("Madagascar","MG"),
		("Malasia","MY"),
		("Malawi","MW"),
		("Mali","ML"),
		("Malta","MT"),
		("Marruecos","MA"),
		("Martinica","MQ"),
		("Mauricio","MU"),
		("Mauritania","MR"),
		("Mayotte","YT"),
		("Micronesia","FM"),
		("Moldavia","MD"),
		("Mongolia","MN"),
		("Montenegro","ME"),
		("Montserrat","MS"),
		("Mozambique","MZ"),
		("Namibia","NA"),
		("Nauru","NR"),
		("Nepal","NP"),
		("Nicaragua","NI"),
		("Niger","NE"),
		("Nigeria","NG"),
		("Niue","NU"),
		("Noruega","NO"),
		("Nueva Caledonia","NC"),
		("Nueva Zelanda","NZ"),
		("Omán","OM"),
		("Países Bajos","NL"),
		("Pakistán","PK"),
		("Palau","PW"),
		("Palestina","PS"),
		("Panamá","PA"),
		("Papúa Nueva Guinea","PG"),
		("Paraguay","PY"),
		("Perú","PE"),
		("Polinesia Francesa","PF"),
		("Polonia","PL"),
		("Portugal","PT"),
		("Puerto Rico","PR"),
		("Qatar","QA"),
		("Reino Unido","GB"),
		("República Centroafricana","CF"),
		("República Checa","CZ"),
		("República Dominicana","DO"),
		("República de Sudán del Sur","SS"),
		("Reunión","RE"),
		("Ruanda","RW"),
		("Rumanía","RO"),
		("Rusia","RU"),
		("Sahara Occidental","EH"),
		("Samoa","WS"),
		("Samoa Americana","AS"),
		("San Bartolomé","BL"),
		("San Cristóbal y Nieves","KN"),
		("San Marino","SM"),
		("San Martín (Francia)","MF"),
		("San Pedro y Miquelón","PM"),
		("San Vicente y las Granadinas","VC"),
		("Santa Elena","SH"),
		("Santa Lucía","LC"),
		("Santo Tomé y Príncipe","ST"),
		("Senegal","SN"),
		("Serbia","RS"),
		("Seychelles","SC"),
		("Sierra Leona","SL"),
		("Singapur","SG"),
		("Sint Maarten","SX"),
		("Siria","SY"),
		("Somalia","SO"),
		("Sri lanka","LK"),
		("Sudáfrica","ZA"),
		("Sudán","SD"),
		("Suecia","SE"),
		("Suiza","CH"),
		("Surinám","SR"),
		("Svalbard y Jan Mayen","SJ"),
		("Swazilandia","SZ"),
		("Tayikistán","TJ"),
		("Tailandia","TH"),
		("Taiwán","TW"),
		("Tanzania","TZ"),
		("Territorio Británico del Océano Índico","IO"),
		("Territorios Australes y Antárticas Franceses","TF"),
		("Timor Oriental","TL"),
		("Togo","TG"),
		("Tokelau","TK"),
		("Tonga","TO"),
		("Trinidad y Tobago","TT"),
		("Tunez","TN"),
		("Turkmenistán","TM"),
		("Turquía","TR"),
		("Tuvalu","TV"),
		("Ucrania","UA"),
		("Uganda","UG"),
		("Uruguay","UY"),
		("Uzbekistán","UZ"),
		("Vanuatu","VU"),
		("Venezuela","VE"),
		("Vietnam","VN"),
		("Wallis y Futuna","WF"),
		("Yemen","YE"),
		("Yibuti","DJ"),
		("Zambia","ZM"),
		("Zimbabue","ZW");
		
	
INSERT INTO generos (nombre) VALUES
	("Plataformas"),
	("Puzzles"),
	("Metroidvania"),
	("Run n' Gun"),
	("Acción y Aventura");

INSERT INTO plataformas (nombre) VALUES
	("PC"),
	("Xbox one"),
	("Xbox Series X/S"),
	("Playstation 4"),
	("Playstation 5"),
	("Switch");

INSERT INTO clasificaciones (nombre, edad_minima) VALUES
	("Early Childhood","03"),
	("Everyone", "06"),
	("Everyone 10+", "10"),
	("Teen", "13"),
	("Mature", "17"),
	("Adulst Only", "18"),
	("Rating Pending", NULL);

INSERT INTO jugadores (nombre, nacimiento, id_pais) VALUES
	("Ivan Maldonado", "2003-01-01", 141),
	("Luis Andrés", "2000-01-03", 141),
	("Sebastian Andrade", "1997-05-05", 141),
	("Edgar Pinto", "1987-01-23", 141),
	("Piolin Adyacente", "2005-03-15",141);

INSERT INTO videojuegos (titulo, fecha_salida, desarrolladora, id_clasificacion, id_plataforma) VALUES
	("Megaman x4", "1997-08-01", "Capcom", 2, 1),
	("Celeste", "2018-01-25", "Maddy Thorson", 3, 2),
	("Daxter", "2006-03-14", "Ready At Dawn", 3,4),
	("Hollow Knight", "2017-02-24", "Team Cherry",3,6),
	("Fez", "2012-02-13", "Phil Fish",2,1);

INSERT INTO jugadores_x_videojuegos (id_jugador, id_videojuego) VALUES
	(1,1),
	(1,4),
	(2,2),
	(2,5),
	(3,3),
	(4,4),
	(5,1),
	(4,1),
	(5,5),
	(2,3);

INSERT INTO videojuegos_x_generos (id_videojuego, id_genero) VALUES
	(1,1),
	(1,4),
	(2,1),
	(3,5),
	(3,1),
	(4,3),
	(5,1),
	(5,2),
	(3,2),
	(2,2),
	(4,1);